services:
  frontend:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    ports:
      -"8080:8080"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pulsewatch
      - SPRING_DATASOURCE_USERNAME=pulsewatch
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: ./worker

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pulsewatch
      - SPRING_DATASOURCE_USERNAME=pulsewatch
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

    depends_on:
      - postgres:
          condition: service_healthy

      - rabbitmq:
          condition: service_healthy


  postgres:
    image: postgres:18
    
    environment:
      - POSTGRES_DG=pulsewatch
      - POSTGRES_USER=pulsewatch
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMAQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:

  rabbitmq_data: