spring.mail.host=${SES_SMTP_HOST}
spring.mail.port=${SES_SMTP_PORT}
spring.mail.username=${SES_SMTP_USERNAME}
spring.mail.password=${SES_SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

pulsewatch.email.from=${PULSEWATCH_EMAIL_FROM}
pulsewatch.email.to=${PULSEWATCH_EMAIL_TO}