spring.jpa.hibernate.ddl-auto=update
pulsewatch.email.aws-region=${AWS_REGION:us-east-1}
pulsewatch.email.from=${PULSEWATCH_EMAIL_FROM:}
pulsewatch.email.to=${PULSEWATCH_EMAIL_TO:}

spring.mail.host=${SES_SMTP_HOST}
spring.mail.port=${SES_SMTP_PORT}
spring.mail.username=${SES_SMTP_USERNAME}
spring.mail.password=${SES_SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true